[package]
name = "innodb_recovery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
crc = "3.2.1"
simple_endian = "0.3.2"
